### ISSUE TITLE
syn::export::toTokens; could not be found

### ISSUE THREAD

**Issue by jakevossen5** [rrevenantt/better_typeid#3] opened 2021-01-07 23:40 UTC
Running `cargo check` in `better_typeid_derive` gives me this error (on stable and nightly)

```
error[E0432]: unresolved import `syn::export`
 --> better_typeid_derive/src/lib.rs:5:10
  |
5 | use syn::export::ToTokens;
  |          ^^^^^^ could not find `export` in `syn`
```

Seems like NuShell had a similar issue a bit ago and fixed it by pinning an older version of syn: https://github.com/nushell/nushell/issues/2867

Note I am actually here because of an issue with antlr4rust: https://github.com/rrevenantt/antlr4rust

**Comment by rrevenantt** [comment] 2021-01-07 23:54
yeah, caused by recent `syn` update, I will try to fix it tomorrow. Meanwhile as temporary fix you can add lower version in your cargo.toml
```toml
[dev-dependencies]
syn="=1.0.56"
```

**Comment by rrevenantt** [comment] 2021-01-08 12:43
Should be fixed now, looks like it was originally caused by intellij-rust not respecting `#[doc(hidden)]` attribute when automatically adding imports.

**Closed as completed by rrevenantt** 2021-01-08 12:43 UTC
